version: '3.8'
services:
  db-mysql:
    platform: linux/amd64	
    image: mysql:5.7.40
    restart: always
    environment:
      - MYSQL_DATABASE=backend_nodejs
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"